# Generated by Django 5.1.1 on 2025-03-17 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapingtask',
            name='current_query',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scrapingtask',
            name='processed_queries',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scrapingtask',
            name='total_queries',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='TaskLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('level', models.CharField(max_length=10)),
                ('message', models.TextField()),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='automation.scrapingtask')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
