# Generated by Django 5.1.1 on 2025-03-17 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0003_scrapingtask_serp_results_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='tasklog',
            index=models.Index(fields=['timestamp'], name='automation__timesta_1fa42f_idx'),
        ),
        migrations.AddIndex(
            model_name='tasklog',
            index=models.Index(fields=['task', 'timestamp'], name='automation__task_id_38c34c_idx'),
        ),
    ]
