country_name_mapping = {
    'Italia': 'Italy',
    'España': 'Spain',
    'Alemania': 'Germany',
    'Francia': 'France',
    'Brasil': 'Brazil',
    'Argentina': 'Argentina',
    'México': 'Mexico',
    'Chile': 'Chile',
    'Portugal': 'Portugal',
    'Colombia': 'Colombia',
    'Grecia': 'Greece',
    'India': 'India',
    'Japón': 'Japan',
    'China': 'China',
    'Tailandia': 'Thailand',
    'Australia': 'Australia',
    'Estados Unidos': 'United States',
    'Reino Unido': 'United Kingdom',
    'Canadá': 'Canada',
    'Países Bajos': 'Netherlands',
    'Bélgica': 'Belgium',
    'Suiza': 'Switzerland',
    'Suecia': 'Sweden',
    'Noruega': 'Norway',
    'Dinamarca': 'Denmark',
    'Finlandia': 'Finland',
    'Austria': 'Austria',
    'Irlanda': 'Ireland',
    'Islandia': 'Iceland',
    'Nueva Zelanda': 'New Zealand',
    'Sudáfrica': 'South Africa',
    'Egipto': 'Egypt',
    'Turquía': 'Turkey',
    'Rusia': 'Russia',
    'Corea del Sur': 'South Korea',
    'Vietnam': 'Vietnam',
    'Indonesia': 'Indonesia',
    'Filipinas': 'Philippines',
    'Malasia': 'Malaysia',
    'Singapur': 'Singapore',
    'Túnez': 'Tunisia',
    'Marruecos': 'Morocco'
}

city_name_mapping = {
    'A Coruña': 'A Coruña',
    'Airlie Beach': 'Airlie Beach',
    'Albufeira': 'Albufeira',
    'Amsterdam': 'Amsterdam',
    'Angers': 'Angers',
    'Atenas': 'Athens',
    'Bangkok': 'Bangkok',
    'Barcelona': 'Barcelona',
    'Barranquilla': 'Barranquilla',
    'Berlin': 'Berlin',
    'Bilbao': 'Bilbao',
    'Bogotá': 'Bogotá',
    'Bolonia': 'Bologna',
    'Boston': 'Boston',
    'Braga': 'Braga',
    'Bruselas': 'Brussels',
    'Bucarest': 'Bucharest',
    'Budapest': 'Budapest',
    'Buenos Aires': 'Buenos Aires',
    'Calcuta': 'Kolkata',
    'Cancún': 'Cancun',
    'Cartagena de indias': 'Cartagena',
    'Cerdeña': 'Sardinia',
    'Ciudad de México': 'Mexico City',
    'Ciudad de Panama': 'Panama City',
    'Coimbra': 'Coimbra',
    'Copenhague': 'Copenhagen',
    'Córdoba': 'Córdoba',
    'Dubai': 'Dubai',
    'Dublin': 'Dublin',
    'El Cairo': 'Cairo',
    'El Calafate': 'El Calafate',
    'Estambul': 'Istanbul',
    'Estocolmo': 'Stockholm',
    'Faro': 'Faro',
    'Florencia': 'Florence',
    'Hawaii': 'Hawaii',
    'Ibiza': 'Ibiza',
    'Isla de Mallorca': 'Mallorca',
    'Javea': 'Jávea',
    'Key West': 'Key West',
    'Kioto': 'Kyoto',
    'Lagos': 'Lagos',
    'Las vegas': 'Las Vegas',
    'Lisboa': 'Lisbon',
    'Londres': 'London',
    'Los Angeles': 'Los Angeles',
    'Madrid': 'Madrid',
    'Malaga': 'Malaga',
    'Malta': 'Malta',
    'Marrakesh': 'Marrakesh',
    'Medellín': 'Medellin',
    'Melbourne': 'Melbourne',
    'Miami': 'Miami',
    'Miami Beach': 'Miami Beach',
    'Milan': 'Milan',
    'Montevideo': 'Montevideo',
    'Mykonos': 'Mykonos',
    'New Orleans': 'New Orleans',
    'New York': 'New York',
    'Niza': 'Nice',
    'Nueva Delhi': 'New Delhi',
    'Orlando': 'Orlando',
    'Osaka': 'Osaka',
    'Paris': 'Paris',
    'Pekin': 'Beijing',
    'Perth': 'Perth',
    'Phuket': 'Phuket',
    'Playa del Carmen': 'Playa del Carmen',
    'Porto': 'Porto',
    'Praga': 'Prague',
    'Puerto Limón': 'Puerto Limón',
    'Puerto Rico': 'Puerto Rico',
    'Puerto Vallarta': 'Puerto Vallarta',
    'Punta Cana': 'Punta Cana',
    'Punta del Este': 'Punta del Este',
    'Quarteira': 'Quarteira',
    'Reikiavik': 'Reykjavik',
    'Rio de Janeiro': 'Rio de Janeiro',
    'Roma': 'Rome',
    'Saint Barthelemy': 'Saint Barthelemy',
    'Salvador de Bahia': 'Salvador',
    'Samaná Costa Norte': 'Samana',
    'San Agustin': 'San Agustin',
    'San Carlos de Bariloche': 'Bariloche',
    'San Diego': 'San Diego',
    'San Francisco': 'San Francisco',
    'Santiago de Chile': 'Santiago',
    'Santiago de Compostela': 'Santiago de Compostela',
    'Santo Domingo': 'Santo Domingo',
    'Savannah': 'Savannah',
    'Seul': 'Seoul',
    'Sevilla': 'Seville',
    'Shanghai': 'Shanghai',
    'Sicilia': 'Sicily',
    'Singapur': 'Singapore',
    'Sintra': 'Sintra',
    'Sofia': 'Sofia',
    'Sydney': 'Sydney',
    'São Paulo': 'Sao Paulo',
    'Tel Aviv': 'Tel Aviv',
    'Tijuana': 'Tijuana',
    'Tokio': 'Tokyo',
    'Toledo': 'Toledo',
    'Tunez': 'Tunis',
    'Ushuaia': 'Ushuaia',
    'Valencia': 'Valencia',
    'Vancouver': 'Vancouver',
    'Varsovia': 'Warsaw',
    'Venecia': 'Venice',
    'Viena': 'Vienna',
    'Washington DC': 'Washington DC'
}
