from automation.models import Category

Category.objects.filter(title="Librerías").update(title="Bookshops")
Category.objects.filter(title="Campo de Fútbol").update(title="Football field")
Category.objects.filter(title="Telefonos y Cartas SIM").update(title="Cell phone store")
Category.objects.filter(title="Sex Shops").update(title="Sex Shops")
Category.objects.filter(title="Herbolario").update(title="Herbalists")
Category.objects.filter(title="Tiendas de Té").update(title="Tea Shops")
Category.objects.filter(title="Licores y vinos").update(title="Liquors and wines")
Category.objects.filter(title="Comida en Conserva").update(title="Canned Food")
Category.objects.filter(title="Tienda Gourmet").update(title="Gourmet grocery store")
Category.objects.filter(title="Tiendas Especializadas").update(title="SPECIALIZED STORES")
Category.objects.filter(title="Tiendas de Cosméticos").update(title="Cosmetics store")
Category.objects.filter(title="Ropa y Artículos Deportivos").update(title="Sports Apparel and Sporting Goods")
Category.objects.filter(title="Zapatería").update(title="Shoe stores")
Category.objects.filter(title="Moda Tradicional Local").update(title="Traditional Local Fashion")
Category.objects.filter(title="Lenceria Femenina").update(title="Women's Lingerie")
Category.objects.filter(title="Moda Hombre").update(title="Men's clothing store")
Category.objects.filter(title="Moda Mujer").update(title="Women's clothing store")
Category.objects.filter(title="Ropa").update(title="CLOTHING")
Category.objects.filter(title="Outlets").update(title="Outlets")
Category.objects.filter(title="Centros comerciales").update(title="Shopping Centres")
Category.objects.filter(title="Milla de Oro").update(title="Golden Mile")
Category.objects.filter(title="Tiendas de Barrio").update(title="Grocery store")
Category.objects.filter(title="Supermercados locales").update(title="Supermarkets")
Category.objects.filter(title="Mercados Locales").update(title="Fresh food market")
Category.objects.filter(title="Artesaría local").update(title="Local craftsmanship")
Category.objects.filter(title="Souvenirs").update(title="Souvenirs")
Category.objects.filter(title="Musica y Folclore").update(title="Music and Folk")
Category.objects.filter(title="Estadio Olimpico").update(title="Olympic Stadium")
Category.objects.filter(title="Centro Cultural").update(title="Cultural Center")
Category.objects.filter(title="Parques y Jardines Públicos").update(title="Public Parks and Gardens")
Category.objects.filter(title="Casa Museo").update(title="Memorial House")
Category.objects.filter(title="Museo Inmersivo").update(title="Immersive Museum")
Category.objects.filter(title="Miradores").update(title="View Points")
Category.objects.filter(title="Campo de Béisbol").update(title="Baseball Field")
Category.objects.filter(title="Pista de Padel").update(title="Padel club")
Category.objects.filter(title="Campo de Tenis").update(title="Tennis court")
Category.objects.filter(title="Circuitos de Velocidad").update(title="Race tracks")
Category.objects.filter(title="Estación de Esquí").update(title="Ski Resort")
Category.objects.filter(title="Campo de Golf").update(title="Golf court")
Category.objects.filter(title="Deportes de Campo").update(title="Field Sports")
Category.objects.filter(title="Bolos").update(title="Bowling")
Category.objects.filter(title="Piscina Deportiva").update(title="Sports Swimming Pool")
Category.objects.filter(title="Yoga").update(title="Yoga")
Category.objects.filter(title="Tai Chi").update(title="Tai Chi")
Category.objects.filter(title="Gimnasio").update(title="Gym")
Category.objects.filter(title="Deportes de interior").update(title="INDOOR SPORTS")
Category.objects.filter(title="Piscinas").update(title="Pools")
Category.objects.filter(title="Vela").update(title="Sail")
Category.objects.filter(title="Wakeboard").update(title="Wakeboard")
Category.objects.filter(title="Buceo").update(title="Scuba Diving")
Category.objects.filter(title="Bodyboard").update(title="Bodyboard")
Category.objects.filter(title="Kitesurf").update(title="Kitesurf")
Category.objects.filter(title="Surf").update(title="Surf")
Category.objects.filter(title="Deportes Acuaticos").update(title="WATER SPORTS")
Category.objects.filter(title="Rutas de Peregrinaje").update(title="Pilgrimage Routes")
Category.objects.filter(title="Rutas de Senderismo").update(title="Trekking & Hiking")
Category.objects.filter(title="Parques Naturales").update(title="Natural Parks")
Category.objects.filter(title="Deportes de Aventura").update(title="Adventure Sports")
Category.objects.filter(title="Naturaleza y Aventura").update(title="Nature & Adventure")
Category.objects.filter(title="Cines").update(title="Cinemas")
Category.objects.filter(title="Zoo").update(title="Zoo")
Category.objects.filter(title="Parques de atracciones").update(title="Amusement Parks")
Category.objects.filter(title="Centros de entretenimiento Infantil").update(title="Children's amusement center")
Category.objects.filter(title="En Familia").update(title="Family Plans")
Category.objects.filter(title="Playas").update(title="Popular Beaches")
Category.objects.filter(title="Paseo Urbano").update(title="Urban Walk")
Category.objects.filter(title="Tour Aéreo").update(title="Air Tour")
Category.objects.filter(title="Tour Aventura").update(title="Adventure Tour")
Category.objects.filter(title="Paseos en Barco").update(title="Boat Tour")
Category.objects.filter(title="Tour en Coche de Caballos").update(title="Horse-drawn carriage tour")
Category.objects.filter(title="Tours en Bici-Taxi").update(title="Bicitaxi Tours")
Category.objects.filter(title="Tours en Barco").update(title="Boat Tours")
Category.objects.filter(title="Tour de Bicicletas").update(title="Bike Tours")
Category.objects.filter(title="Excursión de 1 día").update(title="One Day Trip")
Category.objects.filter(title="Guia turístico").update(title="Tourist guide")
Category.objects.filter(title="Tour Guiado").update(title="Guided Tour")
Category.objects.filter(title="Museos").update(title="Museums")
Category.objects.filter(title="Monumentos").update(title="Monuments")
Category.objects.filter(title="Edificios Emblemáticos").update(title="Emblematic Buildings")
Category.objects.filter(title="Patrimonio histórico").update(title="Historical Heritage")
# Block 3: Update queries

Category.objects.filter(title="Veterinario").update(title="VETERINARY")
Category.objects.filter(title="Protección Legal").update(title="Legal Counseling")
Category.objects.filter(title="Dentista").update(title="Dentist")
Category.objects.filter(title="Farmacia").update(title="Pharmacies")
Category.objects.filter(title="Médico Privado").update(title="Private Doctor")
Category.objects.filter(title="Emergencias").update(title="Medical Emergencies")
Category.objects.filter(title="Estación de Metro").update(title="Metro/Subway Station")
Category.objects.filter(title="Estación de Autobuses").update(title="Bus Station")
Category.objects.filter(title="Estación de Tren").update(title="Train Station")
Category.objects.filter(title="Transporte Público").update(title="Public Transportation")
Category.objects.filter(title="Chofer privado con vehículo").update(title="Private driver with vehicle")
Category.objects.filter(title="Taxi").update(title="Taxi")
Category.objects.filter(title="Transporte Privado").update(title="Private Transportation")
Category.objects.filter(title="Segway").update(title="Segway")
Category.objects.filter(title="Alquiler Limusina").update(title="Limo Rental")
Category.objects.filter(title="Alquiler Ropa").update(title="Clothing Rental")
Category.objects.filter(title="Alquiler Motos de agua").update(title="Jet Ski Rental")
Category.objects.filter(title="Alquiler Barcos").update(title="Boat rental service")
Category.objects.filter(title="Alquiler Patinete Eléctrico").update(title="Electric Scooter Rental")
Category.objects.filter(title="Alquiler Bicicletas").update(title="Bicycle rental service")
Category.objects.filter(title="Alquiler Motos").update(title="Motorcycle rental agency")
Category.objects.filter(title="Alquiler Coches").update(title="Car rental")
Category.objects.filter(title="Bingo").update(title="Bingo")
Category.objects.filter(title="Casino").update(title="Casino")
Category.objects.filter(title="Ocio Nocturno").update(title="Night Leisure")
Category.objects.filter(title="Pub").update(title="Pub")
Category.objects.filter(title="Lounge bar").update(title="Lounge bar")
Category.objects.filter(title="Discotecas").update(title="DiscothÃ¨que")
Category.objects.filter(title="Local Nocturno").update(title="Night club")
Category.objects.filter(title="Cocktelería").update(title="Cocktail Bar")
Category.objects.filter(title="Bar con Música").update(title="Music Bars")
Category.objects.filter(title="Aperitivos y comida rápida").update(title="Snacks and fast food")
Category.objects.filter(title="Pub Irlandés").update(title="Irish Pubs")
Category.objects.filter(title="Áticos y Azoteas Bar").update(title="Rooftop Bars")
Category.objects.filter(title="Guardería de Mascotas").update(title="Pet Day Care")
Category.objects.filter(title="Niñera").update(title="Babysitter")
Category.objects.filter(title="Cajeros Automáticos").update(title="ATMs")
Category.objects.filter(title="Tintorería").update(title="Dry cleaner")
Category.objects.filter(title="Lavandería Autoservicio").update(title="Laundromat")
Category.objects.filter(title="Consigna de Equipajes").update(title="Luggage storage")
Category.objects.filter(title="Clases de idiomas").update(title="Language classes")
Category.objects.filter(title="Espacios de Coworking").update(title="Coworking spaces")
Category.objects.filter(title="Bodegas").update(title="Winery")
Category.objects.filter(title="Bares deportivos").update(title="Sports bars")
Category.objects.filter(title="Heladerías").update(title="Ice Cream Shops")
Category.objects.filter(title="Salón de Té").update(title="Teahouse")
Category.objects.filter(title="Cafetería").update(title="Coffee shops")
Category.objects.filter(title="Panaderías y Pasteleria").update(title="Bakeries")
Category.objects.filter(title="Mercados Locales").update(title="Local Markets")
Category.objects.filter(title="Bares").update(title="Bars")
Category.objects.filter(title="Brunch").update(title="Brunch")
Category.objects.filter(title="Chiringuito").update(title="Beach bar")
Category.objects.filter(title="Beach Club").update(title="Beach club")
Category.objects.filter(title="Comida Alemana").update(title="German food")
Category.objects.filter(title="Comida Rusa").update(title="Russian Food")
# Block 4: Update queries

Category.objects.filter(title="Comida Etíope").update(title="Ethiopian food")
Category.objects.filter(title="Comida Marroquí").update(title="Moroccan food")
Category.objects.filter(title="Comida Brasileña").update(title="Brazilian food")
Category.objects.filter(title="Comida Argentina").update(title="Argentinian food")
Category.objects.filter(title="Restaurante Vietnamita").update(title="Vietnamese food")
Category.objects.filter(title="Comida Peruana").update(title="Peruvian Food")
Category.objects.filter(title="Comida Portuguesa").update(title="Portuguese food")
Category.objects.filter(title="Comida Coreana").update(title="Korean Food")
Category.objects.filter(title="Comida Turca").update(title="Turkish food")
Category.objects.filter(title="Comida Libanesa").update(title="Lebanese food")
Category.objects.filter(title="Comida Griega").update(title="Greek food")
Category.objects.filter(title="Comida Española").update(title="Spanish food")
Category.objects.filter(title="Comida Tailandesa").update(title="Thai Food")
Category.objects.filter(title="Comida India").update(title="Indian food")
Category.objects.filter(title="Comida Mexicana").update(title="Mexican food")
Category.objects.filter(title="Comida Japonesa").update(title="Japanese Food")
Category.objects.filter(title="Comida China").update(title="Chinese food")
Category.objects.filter(title="Comida Francesa").update(title="French Food")
Category.objects.filter(title="Comida Italiana").update(title="Italian food")
Category.objects.filter(title="Restaurantes (Cocina Internacional)").update(title="Rest International Food")
Category.objects.filter(title="Orgánica").update(title="Organic")
Category.objects.filter(title="Vegano").update(title="Vegan / Vegetarian")
Category.objects.filter(title="Arroces").update(title="Rice")
Category.objects.filter(title="Mariscos y Pescado").update(title="Seafood and Fish")
Category.objects.filter(title="Hamburguesería").update(title="Hamburger Restaurant")
Category.objects.filter(title="Carnes - Parrilla").update(title="Meat - Grill")
Category.objects.filter(title="Tapas").update(title="Tapas")
Category.objects.filter(title="Cena con espectáculo").update(title="Dinner with Show")
Category.objects.filter(title="Especialidad Local").update(title="Local Specialties")
Category.objects.filter(title="Restaurantes").update(title="RESTAURANTS")
Category.objects.filter(title="Gourmet").update(title="Gourmet")
Category.objects.filter(title="Guía Michelin").update(title="Michelin Stars")
Category.objects.filter(title="Experiencia Gastronómica").update(title="Gastronomic Experience")
Category.objects.filter(title="Centros de Diálisis").update(title="Dialysis center")
Category.objects.filter(title="Medicina estética y regenerativa").update(title="Regeneration and Aesthetic Medicine")
Category.objects.filter(title="Óptica").update(title="Optician")
Category.objects.filter(title="Entrenador personal").update(title="Personal Trainer")
Category.objects.filter(title="Salón de masajes").update(title="Massage")
Category.objects.filter(title="Balneario / SPA").update(title="Spa")
Category.objects.filter(title="Barbería").update(title="Barbershops")
Category.objects.filter(title="Salón de uñas").update(title="Nails salon")
Category.objects.filter(title="Peluquerías / Salones de belleza").update(title="Hairdresser / Beauty Salon")
Category.objects.filter(title="Hotel Low Cost").update(title="Low cost Hotel")
Category.objects.filter(title="Hotel de aeropuerto").update(title="Airport Hotel")
Category.objects.filter(title="Hotel Temáticos").update(title="Theme Hotel")
Category.objects.filter(title="Hotel resort").update(title="Resort Hotel")
Category.objects.filter(title="Hotel Boutique").update(title="Boutique Hotel")
Category.objects.filter(title="Hoteles").update(title="Hotels")
Category.objects.filter(title="Campings").update(title="Campings")
Category.objects.filter(title="Coliving").update(title="Co-living")
Category.objects.filter(title="Albergues Juveniles").update(title="Youth Hostels")
Category.objects.filter(title="Bed & Breakfast").update(title="Bed & Breakfast")
Category.objects.filter(title="Alquiler vacacional").update(title="Vacation Rental")



Category.objects.filter(title="Operador de Metro").update(title="Subway operator")
Category.objects.filter(title="Musica en Vivo").update(title="Live Music")
Category.objects.filter(title="DiscothÃ¨que").update(title="Disco")
Category.objects.filter(title="Comida Vietnamita").update(title="Vietnamese Food")
Category.objects.filter(title="Comida Portugués").update(title="Portuguese Food")
Category.objects.filter(title="Restaurante Venezolano").update(title="Venezuelan Food")
Category.objects.filter(title="").update(title="")
Category.objects.filter(title="").update(title="")
Category.objects.filter(title="").update(title="")
Category.objects.filter(title="").update(title="")
Category.objects.filter(title="").update(title="")
